//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 

namespace TE3EConnect.te3eOjects.NewBizIntake
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class CftSearchResultRPPerson
    {

        private string searchTermGroupingLabelField;

        private string nameField;

        private string textField;

        private string providerCodeField;

        private string fullTextDocumentIDField;

        private string hitCountField;

        private string textLanguageField;

        private string dataItemIDField;

        private string archCodeField;

        private string attrCodeField;

        private string isExcludedField;

        private string partialTextField;

        private string whereFoundSortOrderField;

        private string statusSortStringField;

        private string whereFoundArchCodeField;

        private string whereFoundAttrCodeField;

        private string whereFoundArchCaptionField;

        private string whereFoundAttrCaptionField;

        private string whereFoundField;

        private string whereFoundItemIDField;

        private string cftSearchTermField;

        private string riskImageField;

        private string searchTermSortOrderField;

        private string debugInfoField;

        private string detailItemIDField;

        private string detailArchCodeField;

        private string openMattersField;

        private string closedMattersField;

        private string opCLMattersField;

        private string whereFoundFrameworkItemIDField;

        private string riskflagTextField;

        private string isSelectedField;

        private string assessmentField;

        private string routedField;

        private string isFilteredField;

        private string corporateTreeImageField;

        private string searchNoField;

        private string clientNameField;

        private string matterNameField;

        private string roleField;

        private string relationshipField;

        private string conflictsContactField;

        private string cftEntityOrMatterIndexField;

        private string ethicalWallImageField;

        private string cftClientIndexField;

        private string entitySanctionLoadField;

        private string isMattercentricHitField;

        private string displayNumberField;

        private string isRouteSelectedField;

        private string entityIndexField;

        private string matterIndexField;

        private string displayTextField;

        private string displayPartialTextField;

        private string displayClientNameField;

        private string displayMatterNameField;

        private string displayNumField;

        private string isFilterAppliedToDetailField;

        private string timekeeperContactField;

        private string nxUserContactField;

        private string displayOpenMattersCountField;

        private string displayClosedMattersCountField;

        private string displayEthicalWallImageField;

        private string displayCorporateTreeImageField;

        private string displayConflictsContactField;

        private string isResultSelectedField;

        private string cftRoleCodeField;

        private string thresholdIndicatorField;

        private string isSearchHasFilterField;

        private string isForceRetrieveDetailsField;

        private string resultsDifferenceImageField;

        private string cftSearchCompareStatusField;

        private string isResultModifiedField;

        private string sourceCollectionField;

        private string isExternalHitField;

        private string fTXSourceTypeField;

        private string pageNumberField;

        private string isViewDifferenceField;

        private string cftFullTextResultsField;

        private string locationOfOccurenceTxt_CCCField;

        private string dateOfOccurenceTxt_CCCField;

        private string relatedPartyIDField;

        private string entIndexField;

        private string mattIndexField;

        private string notesField;

        private string entityIDField;

        private string matterIDField;

        private string linkTypeField;

        private string linkStatusField;

        private string clientNumberField;

        private string matterNumberField;

        private string rPClientNameField;

        private string rPMatterNameField;

        private string clientStatusField;

        private string matterStatusField;

        private string cftRelatedPartyField;

        private string isProspectiveRPItemField;

        private string clientOpenDateField;

        private string clientCloseDateField;

        private string isCreatedPartyField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SearchTermGroupingLabel
        {
            get
            {
                return this.searchTermGroupingLabelField;
            }
            set
            {
                this.searchTermGroupingLabelField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Text
        {
            get
            {
                return this.textField;
            }
            set
            {
                this.textField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ProviderCode
        {
            get
            {
                return this.providerCodeField;
            }
            set
            {
                this.providerCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FullTextDocumentID
        {
            get
            {
                return this.fullTextDocumentIDField;
            }
            set
            {
                this.fullTextDocumentIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string HitCount
        {
            get
            {
                return this.hitCountField;
            }
            set
            {
                this.hitCountField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TextLanguage
        {
            get
            {
                return this.textLanguageField;
            }
            set
            {
                this.textLanguageField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DataItemID
        {
            get
            {
                return this.dataItemIDField;
            }
            set
            {
                this.dataItemIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ArchCode
        {
            get
            {
                return this.archCodeField;
            }
            set
            {
                this.archCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AttrCode
        {
            get
            {
                return this.attrCodeField;
            }
            set
            {
                this.attrCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IsExcluded
        {
            get
            {
                return this.isExcludedField;
            }
            set
            {
                this.isExcludedField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PartialText
        {
            get
            {
                return this.partialTextField;
            }
            set
            {
                this.partialTextField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string WhereFoundSortOrder
        {
            get
            {
                return this.whereFoundSortOrderField;
            }
            set
            {
                this.whereFoundSortOrderField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string StatusSortString
        {
            get
            {
                return this.statusSortStringField;
            }
            set
            {
                this.statusSortStringField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string WhereFoundArchCode
        {
            get
            {
                return this.whereFoundArchCodeField;
            }
            set
            {
                this.whereFoundArchCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string WhereFoundAttrCode
        {
            get
            {
                return this.whereFoundAttrCodeField;
            }
            set
            {
                this.whereFoundAttrCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string WhereFoundArchCaption
        {
            get
            {
                return this.whereFoundArchCaptionField;
            }
            set
            {
                this.whereFoundArchCaptionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string WhereFoundAttrCaption
        {
            get
            {
                return this.whereFoundAttrCaptionField;
            }
            set
            {
                this.whereFoundAttrCaptionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string WhereFound
        {
            get
            {
                return this.whereFoundField;
            }
            set
            {
                this.whereFoundField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string WhereFoundItemID
        {
            get
            {
                return this.whereFoundItemIDField;
            }
            set
            {
                this.whereFoundItemIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CftSearchTerm
        {
            get
            {
                return this.cftSearchTermField;
            }
            set
            {
                this.cftSearchTermField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RiskImage
        {
            get
            {
                return this.riskImageField;
            }
            set
            {
                this.riskImageField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SearchTermSortOrder
        {
            get
            {
                return this.searchTermSortOrderField;
            }
            set
            {
                this.searchTermSortOrderField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DebugInfo
        {
            get
            {
                return this.debugInfoField;
            }
            set
            {
                this.debugInfoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DetailItemID
        {
            get
            {
                return this.detailItemIDField;
            }
            set
            {
                this.detailItemIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DetailArchCode
        {
            get
            {
                return this.detailArchCodeField;
            }
            set
            {
                this.detailArchCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OpenMatters
        {
            get
            {
                return this.openMattersField;
            }
            set
            {
                this.openMattersField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ClosedMatters
        {
            get
            {
                return this.closedMattersField;
            }
            set
            {
                this.closedMattersField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OpCLMatters
        {
            get
            {
                return this.opCLMattersField;
            }
            set
            {
                this.opCLMattersField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string WhereFoundFrameworkItemID
        {
            get
            {
                return this.whereFoundFrameworkItemIDField;
            }
            set
            {
                this.whereFoundFrameworkItemIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RiskflagText
        {
            get
            {
                return this.riskflagTextField;
            }
            set
            {
                this.riskflagTextField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IsSelected
        {
            get
            {
                return this.isSelectedField;
            }
            set
            {
                this.isSelectedField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Assessment
        {
            get
            {
                return this.assessmentField;
            }
            set
            {
                this.assessmentField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Routed
        {
            get
            {
                return this.routedField;
            }
            set
            {
                this.routedField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IsFiltered
        {
            get
            {
                return this.isFilteredField;
            }
            set
            {
                this.isFilteredField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CorporateTreeImage
        {
            get
            {
                return this.corporateTreeImageField;
            }
            set
            {
                this.corporateTreeImageField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SearchNo
        {
            get
            {
                return this.searchNoField;
            }
            set
            {
                this.searchNoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ClientName
        {
            get
            {
                return this.clientNameField;
            }
            set
            {
                this.clientNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MatterName
        {
            get
            {
                return this.matterNameField;
            }
            set
            {
                this.matterNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Role
        {
            get
            {
                return this.roleField;
            }
            set
            {
                this.roleField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Relationship
        {
            get
            {
                return this.relationshipField;
            }
            set
            {
                this.relationshipField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ConflictsContact
        {
            get
            {
                return this.conflictsContactField;
            }
            set
            {
                this.conflictsContactField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CftEntityOrMatterIndex
        {
            get
            {
                return this.cftEntityOrMatterIndexField;
            }
            set
            {
                this.cftEntityOrMatterIndexField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EthicalWallImage
        {
            get
            {
                return this.ethicalWallImageField;
            }
            set
            {
                this.ethicalWallImageField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CftClientIndex
        {
            get
            {
                return this.cftClientIndexField;
            }
            set
            {
                this.cftClientIndexField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EntitySanctionLoad
        {
            get
            {
                return this.entitySanctionLoadField;
            }
            set
            {
                this.entitySanctionLoadField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IsMattercentricHit
        {
            get
            {
                return this.isMattercentricHitField;
            }
            set
            {
                this.isMattercentricHitField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DisplayNumber
        {
            get
            {
                return this.displayNumberField;
            }
            set
            {
                this.displayNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IsRouteSelected
        {
            get
            {
                return this.isRouteSelectedField;
            }
            set
            {
                this.isRouteSelectedField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EntityIndex
        {
            get
            {
                return this.entityIndexField;
            }
            set
            {
                this.entityIndexField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MatterIndex
        {
            get
            {
                return this.matterIndexField;
            }
            set
            {
                this.matterIndexField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DisplayText
        {
            get
            {
                return this.displayTextField;
            }
            set
            {
                this.displayTextField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DisplayPartialText
        {
            get
            {
                return this.displayPartialTextField;
            }
            set
            {
                this.displayPartialTextField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DisplayClientName
        {
            get
            {
                return this.displayClientNameField;
            }
            set
            {
                this.displayClientNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DisplayMatterName
        {
            get
            {
                return this.displayMatterNameField;
            }
            set
            {
                this.displayMatterNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DisplayNum
        {
            get
            {
                return this.displayNumField;
            }
            set
            {
                this.displayNumField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IsFilterAppliedToDetail
        {
            get
            {
                return this.isFilterAppliedToDetailField;
            }
            set
            {
                this.isFilterAppliedToDetailField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TimekeeperContact
        {
            get
            {
                return this.timekeeperContactField;
            }
            set
            {
                this.timekeeperContactField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NxUserContact
        {
            get
            {
                return this.nxUserContactField;
            }
            set
            {
                this.nxUserContactField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DisplayOpenMattersCount
        {
            get
            {
                return this.displayOpenMattersCountField;
            }
            set
            {
                this.displayOpenMattersCountField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DisplayClosedMattersCount
        {
            get
            {
                return this.displayClosedMattersCountField;
            }
            set
            {
                this.displayClosedMattersCountField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DisplayEthicalWallImage
        {
            get
            {
                return this.displayEthicalWallImageField;
            }
            set
            {
                this.displayEthicalWallImageField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DisplayCorporateTreeImage
        {
            get
            {
                return this.displayCorporateTreeImageField;
            }
            set
            {
                this.displayCorporateTreeImageField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DisplayConflictsContact
        {
            get
            {
                return this.displayConflictsContactField;
            }
            set
            {
                this.displayConflictsContactField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IsResultSelected
        {
            get
            {
                return this.isResultSelectedField;
            }
            set
            {
                this.isResultSelectedField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CftRoleCode
        {
            get
            {
                return this.cftRoleCodeField;
            }
            set
            {
                this.cftRoleCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ThresholdIndicator
        {
            get
            {
                return this.thresholdIndicatorField;
            }
            set
            {
                this.thresholdIndicatorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IsSearchHasFilter
        {
            get
            {
                return this.isSearchHasFilterField;
            }
            set
            {
                this.isSearchHasFilterField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IsForceRetrieveDetails
        {
            get
            {
                return this.isForceRetrieveDetailsField;
            }
            set
            {
                this.isForceRetrieveDetailsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ResultsDifferenceImage
        {
            get
            {
                return this.resultsDifferenceImageField;
            }
            set
            {
                this.resultsDifferenceImageField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CftSearchCompareStatus
        {
            get
            {
                return this.cftSearchCompareStatusField;
            }
            set
            {
                this.cftSearchCompareStatusField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IsResultModified
        {
            get
            {
                return this.isResultModifiedField;
            }
            set
            {
                this.isResultModifiedField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SourceCollection
        {
            get
            {
                return this.sourceCollectionField;
            }
            set
            {
                this.sourceCollectionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IsExternalHit
        {
            get
            {
                return this.isExternalHitField;
            }
            set
            {
                this.isExternalHitField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FTXSourceType
        {
            get
            {
                return this.fTXSourceTypeField;
            }
            set
            {
                this.fTXSourceTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PageNumber
        {
            get
            {
                return this.pageNumberField;
            }
            set
            {
                this.pageNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IsViewDifference
        {
            get
            {
                return this.isViewDifferenceField;
            }
            set
            {
                this.isViewDifferenceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CftFullTextResults
        {
            get
            {
                return this.cftFullTextResultsField;
            }
            set
            {
                this.cftFullTextResultsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LocationOfOccurenceTxt_CCC
        {
            get
            {
                return this.locationOfOccurenceTxt_CCCField;
            }
            set
            {
                this.locationOfOccurenceTxt_CCCField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DateOfOccurenceTxt_CCC
        {
            get
            {
                return this.dateOfOccurenceTxt_CCCField;
            }
            set
            {
                this.dateOfOccurenceTxt_CCCField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RelatedPartyID
        {
            get
            {
                return this.relatedPartyIDField;
            }
            set
            {
                this.relatedPartyIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EntIndex
        {
            get
            {
                return this.entIndexField;
            }
            set
            {
                this.entIndexField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MattIndex
        {
            get
            {
                return this.mattIndexField;
            }
            set
            {
                this.mattIndexField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Notes
        {
            get
            {
                return this.notesField;
            }
            set
            {
                this.notesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EntityID
        {
            get
            {
                return this.entityIDField;
            }
            set
            {
                this.entityIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MatterID
        {
            get
            {
                return this.matterIDField;
            }
            set
            {
                this.matterIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LinkType
        {
            get
            {
                return this.linkTypeField;
            }
            set
            {
                this.linkTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LinkStatus
        {
            get
            {
                return this.linkStatusField;
            }
            set
            {
                this.linkStatusField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ClientNumber
        {
            get
            {
                return this.clientNumberField;
            }
            set
            {
                this.clientNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MatterNumber
        {
            get
            {
                return this.matterNumberField;
            }
            set
            {
                this.matterNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RPClientName
        {
            get
            {
                return this.rPClientNameField;
            }
            set
            {
                this.rPClientNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RPMatterName
        {
            get
            {
                return this.rPMatterNameField;
            }
            set
            {
                this.rPMatterNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ClientStatus
        {
            get
            {
                return this.clientStatusField;
            }
            set
            {
                this.clientStatusField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MatterStatus
        {
            get
            {
                return this.matterStatusField;
            }
            set
            {
                this.matterStatusField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CftRelatedParty
        {
            get
            {
                return this.cftRelatedPartyField;
            }
            set
            {
                this.cftRelatedPartyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IsProspectiveRPItem
        {
            get
            {
                return this.isProspectiveRPItemField;
            }
            set
            {
                this.isProspectiveRPItemField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ClientOpenDate
        {
            get
            {
                return this.clientOpenDateField;
            }
            set
            {
                this.clientOpenDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ClientCloseDate
        {
            get
            {
                return this.clientCloseDateField;
            }
            set
            {
                this.clientCloseDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IsCreatedParty
        {
            get
            {
                return this.isCreatedPartyField;
            }
            set
            {
                this.isCreatedPartyField = value;
            }
        }
    }

    ///// <remarks/>
    //[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    //[System.SerializableAttribute()]
    //[System.Diagnostics.DebuggerStepThroughAttribute()]
    //[System.ComponentModel.DesignerCategoryAttribute("code")]
    //[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    //[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    //public partial class NewDataSet
    //{

    //    private CftSearchResultRPPerson[] itemsField;

    //    /// <remarks/>
    //    [System.Xml.Serialization.XmlElementAttribute("CftSearchResultRPPerson")]
    //    public CftSearchResultRPPerson[] Items
    //    {
    //        get
    //        {
    //            return this.itemsField;
    //        }
    //        set
    //        {
    //            this.itemsField = value;
    //        }
    //    }
    //}
}