//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TE3EEntityFramework.Datasource
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomSubjectLine
    {
        public int Id { get; set; }
        public string ClientIndex { get; set; }
        public string ClientName { get; set; }
        public string SpecialSubjectLine { get; set; }
        public string SpecificEmail { get; set; }
    }
}
