//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TE3EEntityFramework.Datasource
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class RCGAMZN_PROD01Entities : DbContext
    {
        public RCGAMZN_PROD01Entities()
            : base("name=RCGAMZN_PROD01Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TeamsDMSConfiguration> TeamsDMSConfigurations { get; set; }
        public virtual DbSet<TeamsDMSOfficeFilter> TeamsDMSOfficeFilters { get; set; }
        public virtual DbSet<TeamsDMSQueue> TeamsDMSQueues { get; set; }
        public virtual DbSet<TeamsDMSQueueLog> TeamsDMSQueueLogs { get; set; }
    
        public virtual int DMS_RetrieveMattersForTeams(Nullable<int> numOfDays)
        {
            var numOfDaysParameter = numOfDays.HasValue ?
                new ObjectParameter("numOfDays", numOfDays) :
                new ObjectParameter("numOfDays", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DMS_RetrieveMattersForTeams", numOfDaysParameter);
        }
    
        public virtual int DMS_RetrieveMattersForTeamsByOffice(Nullable<int> numOfDays, string office)
        {
            var numOfDaysParameter = numOfDays.HasValue ?
                new ObjectParameter("numOfDays", numOfDays) :
                new ObjectParameter("numOfDays", typeof(int));
    
            var officeParameter = office != null ?
                new ObjectParameter("office", office) :
                new ObjectParameter("office", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DMS_RetrieveMattersForTeamsByOffice", numOfDaysParameter, officeParameter);
        }
    
        public virtual int DMS_RetrieveMatterForTeamsByNumber(string mattNum)
        {
            var mattNumParameter = mattNum != null ?
                new ObjectParameter("mattNum", mattNum) :
                new ObjectParameter("mattNum", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DMS_RetrieveMatterForTeamsByNumber", mattNumParameter);
        }
    }
}
