//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TE3EEntityFramework.Datasource
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeamsDMSQueueLog
    {
        public int Id { get; set; }
        public string MatterNumber { get; set; }
        public string MatterName { get; set; }
        public string MatterStatus { get; set; }
        public string TeamsOwners { get; set; }
        public string TeamsMembers { get; set; }
        public Nullable<System.DateTime> ExportedDate { get; set; }
        public string ErrorMessage { get; set; }
        public string WebResponse { get; set; }
    }
}
