//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class CftNewBizRequest {
    
    private string cftNewBizRequestIDField;
    
    private string cftSearchReasonField;
    
    private string clientField;
    
    private string matterField;
    
    private string entityField;
    
    private string displayNameField;
    
    private string requestDateTimeField;
    
    private string jobNumberField;
    
    private string isCreatedMatterField;
    
    private string isCreatedClientField;
    
    private string cftNBRStatusField;
    
    private string currentWorkflowStepField;
    
    private string orgProcField;
    
    private string clientSearchNameIdField;
    
    private string submitterField;
    
    private string finalizeResultField;
    
    private string routeToField;
    
    private string dateRoutedField;
    
    private string dateDecidedField;
    
    private string declineReasonField;
    
    private string declineCommentField;
    
    private string decidedByField;
    
    private string cftSearchAuthorityField;
    
    private string cftAuthorityField;
    
    private string loadNumberField;
    
    private string loadSourceField;
    
    private string loadGroupField;
    
    private string loadBatchIDField;
    
    private string loadFlagField;
    
    private string lastEditedByField;
    
    private string fromCMCaseField;
    
    private string cmCaseField;
    
    private string cftResultViewField;
    
    private string adminCommentsField;
    
    private string adminComments_FormattedTextField;
    
    private string clientMatterCreationRouteToField;
    
    private string isNoSearchNecessaryField;
    
    private CftNewBizRequestDescription[] descriptionField;
    
    private CftNewBizRequestNumber[] numberField;
    
    private CftNewBizRequestBaseUserName[] baseUserNameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CftNewBizRequestID {
        get {
            return this.cftNewBizRequestIDField;
        }
        set {
            this.cftNewBizRequestIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CftSearchReason {
        get {
            return this.cftSearchReasonField;
        }
        set {
            this.cftSearchReasonField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Client {
        get {
            return this.clientField;
        }
        set {
            this.clientField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Matter {
        get {
            return this.matterField;
        }
        set {
            this.matterField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Entity {
        get {
            return this.entityField;
        }
        set {
            this.entityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string DisplayName {
        get {
            return this.displayNameField;
        }
        set {
            this.displayNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string RequestDateTime {
        get {
            return this.requestDateTimeField;
        }
        set {
            this.requestDateTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string JobNumber {
        get {
            return this.jobNumberField;
        }
        set {
            this.jobNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string IsCreatedMatter {
        get {
            return this.isCreatedMatterField;
        }
        set {
            this.isCreatedMatterField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string IsCreatedClient {
        get {
            return this.isCreatedClientField;
        }
        set {
            this.isCreatedClientField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CftNBRStatus {
        get {
            return this.cftNBRStatusField;
        }
        set {
            this.cftNBRStatusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CurrentWorkflowStep {
        get {
            return this.currentWorkflowStepField;
        }
        set {
            this.currentWorkflowStepField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string OrgProc {
        get {
            return this.orgProcField;
        }
        set {
            this.orgProcField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ClientSearchNameId {
        get {
            return this.clientSearchNameIdField;
        }
        set {
            this.clientSearchNameIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Submitter {
        get {
            return this.submitterField;
        }
        set {
            this.submitterField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string FinalizeResult {
        get {
            return this.finalizeResultField;
        }
        set {
            this.finalizeResultField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string RouteTo {
        get {
            return this.routeToField;
        }
        set {
            this.routeToField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string DateRouted {
        get {
            return this.dateRoutedField;
        }
        set {
            this.dateRoutedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string DateDecided {
        get {
            return this.dateDecidedField;
        }
        set {
            this.dateDecidedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string DeclineReason {
        get {
            return this.declineReasonField;
        }
        set {
            this.declineReasonField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string DeclineComment {
        get {
            return this.declineCommentField;
        }
        set {
            this.declineCommentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string DecidedBy {
        get {
            return this.decidedByField;
        }
        set {
            this.decidedByField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CftSearchAuthority {
        get {
            return this.cftSearchAuthorityField;
        }
        set {
            this.cftSearchAuthorityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CftAuthority {
        get {
            return this.cftAuthorityField;
        }
        set {
            this.cftAuthorityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string LoadNumber {
        get {
            return this.loadNumberField;
        }
        set {
            this.loadNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string LoadSource {
        get {
            return this.loadSourceField;
        }
        set {
            this.loadSourceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string LoadGroup {
        get {
            return this.loadGroupField;
        }
        set {
            this.loadGroupField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string LoadBatchID {
        get {
            return this.loadBatchIDField;
        }
        set {
            this.loadBatchIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string LoadFlag {
        get {
            return this.loadFlagField;
        }
        set {
            this.loadFlagField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string LastEditedBy {
        get {
            return this.lastEditedByField;
        }
        set {
            this.lastEditedByField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string FromCMCase {
        get {
            return this.fromCMCaseField;
        }
        set {
            this.fromCMCaseField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CmCase {
        get {
            return this.cmCaseField;
        }
        set {
            this.cmCaseField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CftResultView {
        get {
            return this.cftResultViewField;
        }
        set {
            this.cftResultViewField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string AdminComments {
        get {
            return this.adminCommentsField;
        }
        set {
            this.adminCommentsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string AdminComments_FormattedText {
        get {
            return this.adminComments_FormattedTextField;
        }
        set {
            this.adminComments_FormattedTextField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ClientMatterCreationRouteTo {
        get {
            return this.clientMatterCreationRouteToField;
        }
        set {
            this.clientMatterCreationRouteToField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string IsNoSearchNecessary {
        get {
            return this.isNoSearchNecessaryField;
        }
        set {
            this.isNoSearchNecessaryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Description", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public CftNewBizRequestDescription[] Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Number", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public CftNewBizRequestNumber[] Number {
        get {
            return this.numberField;
        }
        set {
            this.numberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("BaseUserName", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public CftNewBizRequestBaseUserName[] BaseUserName {
        get {
            return this.baseUserNameField;
        }
        set {
            this.baseUserNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class CftNewBizRequestDescription {
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class CftNewBizRequestNumber {
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class CftNewBizRequestBaseUserName {
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class NewDataSet {
    
    private CftNewBizRequest[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("CftNewBizRequest")]
    public CftNewBizRequest[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}
