//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class CollectionStep {
    
    private string stepNumberField;
    
    private string actionField;
    
    private string collectorField;
    
    private string actionPriorityField;
    
    private string isDoneIfInvIsPaidField;
    
    private string isDoneImmediatelyField;
    
    private string daysAfterField;
    
    private string dateSourceTypeListField;
    
    private string actionByTypeListField;
    
    private string commentsField;
    
    private string isCompletedField;
    
    private string completedByField;
    
    private string collectionActorListField;
    
    private string scheduledDateField;
    
    private string actionByUnboundField;
    
    private string collectionActorListUnboundField;
    
    private string collectorUnboundField;
    
    private string scheduledDateUnboundField;
    
    private string printerTemplateField;
    
    private string emailAddrField;
    
    private string emailSubjectField;
    
    private string isStepRepeatedField;
    
    private string emailFromAddressField;
    
    private string emailCCAddressField;
    
    private string emailBCCAddressField;
    
    private string billingOfficeField;
    
    private string matterLanguageField;
    
    private string collectionOfficeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string StepNumber {
        get {
            return this.stepNumberField;
        }
        set {
            this.stepNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Action {
        get {
            return this.actionField;
        }
        set {
            this.actionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Collector {
        get {
            return this.collectorField;
        }
        set {
            this.collectorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ActionPriority {
        get {
            return this.actionPriorityField;
        }
        set {
            this.actionPriorityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string IsDoneIfInvIsPaid {
        get {
            return this.isDoneIfInvIsPaidField;
        }
        set {
            this.isDoneIfInvIsPaidField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string IsDoneImmediately {
        get {
            return this.isDoneImmediatelyField;
        }
        set {
            this.isDoneImmediatelyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string DaysAfter {
        get {
            return this.daysAfterField;
        }
        set {
            this.daysAfterField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string DateSourceTypeList {
        get {
            return this.dateSourceTypeListField;
        }
        set {
            this.dateSourceTypeListField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ActionByTypeList {
        get {
            return this.actionByTypeListField;
        }
        set {
            this.actionByTypeListField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Comments {
        get {
            return this.commentsField;
        }
        set {
            this.commentsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string IsCompleted {
        get {
            return this.isCompletedField;
        }
        set {
            this.isCompletedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CompletedBy {
        get {
            return this.completedByField;
        }
        set {
            this.completedByField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CollectionActorList {
        get {
            return this.collectionActorListField;
        }
        set {
            this.collectionActorListField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ScheduledDate {
        get {
            return this.scheduledDateField;
        }
        set {
            this.scheduledDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ActionByUnbound {
        get {
            return this.actionByUnboundField;
        }
        set {
            this.actionByUnboundField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CollectionActorListUnbound {
        get {
            return this.collectionActorListUnboundField;
        }
        set {
            this.collectionActorListUnboundField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CollectorUnbound {
        get {
            return this.collectorUnboundField;
        }
        set {
            this.collectorUnboundField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ScheduledDateUnbound {
        get {
            return this.scheduledDateUnboundField;
        }
        set {
            this.scheduledDateUnboundField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string PrinterTemplate {
        get {
            return this.printerTemplateField;
        }
        set {
            this.printerTemplateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string EmailAddr {
        get {
            return this.emailAddrField;
        }
        set {
            this.emailAddrField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string EmailSubject {
        get {
            return this.emailSubjectField;
        }
        set {
            this.emailSubjectField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string IsStepRepeated {
        get {
            return this.isStepRepeatedField;
        }
        set {
            this.isStepRepeatedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string EmailFromAddress {
        get {
            return this.emailFromAddressField;
        }
        set {
            this.emailFromAddressField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string EmailCCAddress {
        get {
            return this.emailCCAddressField;
        }
        set {
            this.emailCCAddressField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string EmailBCCAddress {
        get {
            return this.emailBCCAddressField;
        }
        set {
            this.emailBCCAddressField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string BillingOffice {
        get {
            return this.billingOfficeField;
        }
        set {
            this.billingOfficeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string MatterLanguage {
        get {
            return this.matterLanguageField;
        }
        set {
            this.matterLanguageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CollectionOffice {
        get {
            return this.collectionOfficeField;
        }
        set {
            this.collectionOfficeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class NewDataSet {
    
    private CollectionStep[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("CollectionStep")]
    public CollectionStep[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}
