//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TE3EEntityFramework.Datasource.UKGTE3E.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class UKG_TE_3E_PO
    {
        public int ID { get; set; }
        public string Supplier { get; set; }
        public string ShipSite { get; set; }
        public string ShipInstructions { get; set; }
        public string Comments { get; set; }
        public string NxUser { get; set; }
        public string EmailAddress { get; set; }
        public Nullable<System.DateTime> ReqDate { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public string EmployeeName { get; set; }
        public string EmployeeType { get; set; }
        public string ProductBundle_CCC { get; set; }
        public string BundleName { get; set; }
        public string OptionalEquipments { get; set; }
        public string OptionalEquipmentCodes { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string ListItemId { get; set; }
        public Nullable<System.DateTime> ImportedDate { get; set; }
        public string SvcOperation { get; set; }
        public Nullable<int> NumOfAttempt { get; set; }
        public string LogInfo { get; set; }
        public Nullable<bool> IsProcessed { get; set; }
        public Nullable<System.DateTime> ProcessedDate { get; set; }
    }
}
