//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class CostCard {
    
    private string costCardIDField;
    
    private string costIndexField;
    
    private string origCostCardField;
    
    private string officeField;
    
    private string sourceField;
    
    private string workDateField;
    
    private string postDateField;
    
    private string currencyField;
    
    private string currDateField;
    
    private string matterField;
    
    private string billMatterField;
    
    private string timekeeperField;
    
    private string workMattEffDateField;
    
    private string billMattEffDateField;
    
    private string tkprEffDateField;
    
    private string isActiveField;
    
    private string isNBField;
    
    private string resPctField;
    
    private string isNoChargeField;
    
    private string origAmtField;
    
    private string chrgCardField;
    
    private string chargeAmtField;
    
    private string entryUnitTypeField;
    
    private string entryUnitField;
    
    private string workQtyField;
    
    private string workRateField;
    
    private string workAmtField;
    
    private string stdRateField;
    
    private string stdCurrencyField;
    
    private string stdAmtField;
    
    private string languageField;
    
    private string narrativeField;
    
    private string narrative_FormattedTextField;
    
    private string internalCommentsField;
    
    private string costTypeField;
    
    private string transactionTypeField;
    
    private string isHardCostField;
    
    private string taxJurisdictionField;
    
    private string phaseField;
    
    private string taskField;
    
    private string activityField;
    
    private string taxCodeField;
    
    private string editTranTypeField;
    
    private string dispositionField;
    
    private string reasonTypeField;
    
    private string profMasterField;
    
    private string invMasterField;
    
    private string invNumberField;
    
    private string voucherField;
    
    private string invNumField;
    
    private string origQtyField;
    
    private string origCurrencyField;
    
    private string origRateField;
    
    private string inputTaxCodeField;
    
    private string workTypeField;
    
    private string purgeTypeField;
    
    private string wIPRemoveDateField;
    
    private string unitCurrRateField;
    
    private string firmCurrRateField;
    
    private string unitCurrRateStdField;
    
    private string firmCurrRateStdField;
    
    private string wIPQtyField;
    
    private string wIPRateField;
    
    private string wIPAmtField;
    
    private string isDisplayField;
    
    private string loadNumberField;
    
    private string loadSourceField;
    
    private string loadGroupField;
    
    private string rateCalcListField;
    
    private string refCurrencyField;
    
    private string refRateField;
    
    private string refAmtField;
    
    private string isSummarizeField;
    
    private string gLDateField;
    
    private string authTimekeeperField;
    
    private string spvTimekeeperField;
    
    private string parCostIndexField;
    
    private string matrixTaxCodeField;
    
    private string rpt1CurrRateField;
    
    private string rpt2CurrRateField;
    
    private string rpt3CurrRateField;
    
    private string rpt1CurrRateStdField;
    
    private string rpt2CurrRateStdField;
    
    private string rpt3CurrRateStdField;
    
    private string prevProfMasterField;
    
    private string conversionRefNumField;
    
    private string wHTaxCodeField;
    
    private string wHTaxReasonField;
    
    private string lastPurgeTypeField;
    
    private string phase2Field;
    
    private string task2Field;
    
    private string activity2Field;
    
    private CostCardDescription[] descriptionField;
    
    private CostCardNumber[] numberField;
    
    private CostCardCode[] codeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CostCardID {
        get {
            return this.costCardIDField;
        }
        set {
            this.costCardIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CostIndex {
        get {
            return this.costIndexField;
        }
        set {
            this.costIndexField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string OrigCostCard {
        get {
            return this.origCostCardField;
        }
        set {
            this.origCostCardField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Office {
        get {
            return this.officeField;
        }
        set {
            this.officeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Source {
        get {
            return this.sourceField;
        }
        set {
            this.sourceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string WorkDate {
        get {
            return this.workDateField;
        }
        set {
            this.workDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string PostDate {
        get {
            return this.postDateField;
        }
        set {
            this.postDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Currency {
        get {
            return this.currencyField;
        }
        set {
            this.currencyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CurrDate {
        get {
            return this.currDateField;
        }
        set {
            this.currDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Matter {
        get {
            return this.matterField;
        }
        set {
            this.matterField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string BillMatter {
        get {
            return this.billMatterField;
        }
        set {
            this.billMatterField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Timekeeper {
        get {
            return this.timekeeperField;
        }
        set {
            this.timekeeperField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string WorkMattEffDate {
        get {
            return this.workMattEffDateField;
        }
        set {
            this.workMattEffDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string BillMattEffDate {
        get {
            return this.billMattEffDateField;
        }
        set {
            this.billMattEffDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string TkprEffDate {
        get {
            return this.tkprEffDateField;
        }
        set {
            this.tkprEffDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string IsActive {
        get {
            return this.isActiveField;
        }
        set {
            this.isActiveField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string IsNB {
        get {
            return this.isNBField;
        }
        set {
            this.isNBField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ResPct {
        get {
            return this.resPctField;
        }
        set {
            this.resPctField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string IsNoCharge {
        get {
            return this.isNoChargeField;
        }
        set {
            this.isNoChargeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string OrigAmt {
        get {
            return this.origAmtField;
        }
        set {
            this.origAmtField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ChrgCard {
        get {
            return this.chrgCardField;
        }
        set {
            this.chrgCardField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ChargeAmt {
        get {
            return this.chargeAmtField;
        }
        set {
            this.chargeAmtField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string EntryUnitType {
        get {
            return this.entryUnitTypeField;
        }
        set {
            this.entryUnitTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string EntryUnit {
        get {
            return this.entryUnitField;
        }
        set {
            this.entryUnitField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string WorkQty {
        get {
            return this.workQtyField;
        }
        set {
            this.workQtyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string WorkRate {
        get {
            return this.workRateField;
        }
        set {
            this.workRateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string WorkAmt {
        get {
            return this.workAmtField;
        }
        set {
            this.workAmtField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string StdRate {
        get {
            return this.stdRateField;
        }
        set {
            this.stdRateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string StdCurrency {
        get {
            return this.stdCurrencyField;
        }
        set {
            this.stdCurrencyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string StdAmt {
        get {
            return this.stdAmtField;
        }
        set {
            this.stdAmtField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Language {
        get {
            return this.languageField;
        }
        set {
            this.languageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Narrative {
        get {
            return this.narrativeField;
        }
        set {
            this.narrativeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Narrative_FormattedText {
        get {
            return this.narrative_FormattedTextField;
        }
        set {
            this.narrative_FormattedTextField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string InternalComments {
        get {
            return this.internalCommentsField;
        }
        set {
            this.internalCommentsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CostType {
        get {
            return this.costTypeField;
        }
        set {
            this.costTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string TransactionType {
        get {
            return this.transactionTypeField;
        }
        set {
            this.transactionTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string IsHardCost {
        get {
            return this.isHardCostField;
        }
        set {
            this.isHardCostField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string TaxJurisdiction {
        get {
            return this.taxJurisdictionField;
        }
        set {
            this.taxJurisdictionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Phase {
        get {
            return this.phaseField;
        }
        set {
            this.phaseField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Task {
        get {
            return this.taskField;
        }
        set {
            this.taskField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Activity {
        get {
            return this.activityField;
        }
        set {
            this.activityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string TaxCode {
        get {
            return this.taxCodeField;
        }
        set {
            this.taxCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string EditTranType {
        get {
            return this.editTranTypeField;
        }
        set {
            this.editTranTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Disposition {
        get {
            return this.dispositionField;
        }
        set {
            this.dispositionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ReasonType {
        get {
            return this.reasonTypeField;
        }
        set {
            this.reasonTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ProfMaster {
        get {
            return this.profMasterField;
        }
        set {
            this.profMasterField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string InvMaster {
        get {
            return this.invMasterField;
        }
        set {
            this.invMasterField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string InvNumber {
        get {
            return this.invNumberField;
        }
        set {
            this.invNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Voucher {
        get {
            return this.voucherField;
        }
        set {
            this.voucherField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string InvNum {
        get {
            return this.invNumField;
        }
        set {
            this.invNumField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string OrigQty {
        get {
            return this.origQtyField;
        }
        set {
            this.origQtyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string OrigCurrency {
        get {
            return this.origCurrencyField;
        }
        set {
            this.origCurrencyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string OrigRate {
        get {
            return this.origRateField;
        }
        set {
            this.origRateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string InputTaxCode {
        get {
            return this.inputTaxCodeField;
        }
        set {
            this.inputTaxCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string WorkType {
        get {
            return this.workTypeField;
        }
        set {
            this.workTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string PurgeType {
        get {
            return this.purgeTypeField;
        }
        set {
            this.purgeTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string WIPRemoveDate {
        get {
            return this.wIPRemoveDateField;
        }
        set {
            this.wIPRemoveDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string UnitCurrRate {
        get {
            return this.unitCurrRateField;
        }
        set {
            this.unitCurrRateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string FirmCurrRate {
        get {
            return this.firmCurrRateField;
        }
        set {
            this.firmCurrRateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string UnitCurrRateStd {
        get {
            return this.unitCurrRateStdField;
        }
        set {
            this.unitCurrRateStdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string FirmCurrRateStd {
        get {
            return this.firmCurrRateStdField;
        }
        set {
            this.firmCurrRateStdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string WIPQty {
        get {
            return this.wIPQtyField;
        }
        set {
            this.wIPQtyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string WIPRate {
        get {
            return this.wIPRateField;
        }
        set {
            this.wIPRateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string WIPAmt {
        get {
            return this.wIPAmtField;
        }
        set {
            this.wIPAmtField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string IsDisplay {
        get {
            return this.isDisplayField;
        }
        set {
            this.isDisplayField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string LoadNumber {
        get {
            return this.loadNumberField;
        }
        set {
            this.loadNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string LoadSource {
        get {
            return this.loadSourceField;
        }
        set {
            this.loadSourceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string LoadGroup {
        get {
            return this.loadGroupField;
        }
        set {
            this.loadGroupField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string RateCalcList {
        get {
            return this.rateCalcListField;
        }
        set {
            this.rateCalcListField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string RefCurrency {
        get {
            return this.refCurrencyField;
        }
        set {
            this.refCurrencyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string RefRate {
        get {
            return this.refRateField;
        }
        set {
            this.refRateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string RefAmt {
        get {
            return this.refAmtField;
        }
        set {
            this.refAmtField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string IsSummarize {
        get {
            return this.isSummarizeField;
        }
        set {
            this.isSummarizeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string GLDate {
        get {
            return this.gLDateField;
        }
        set {
            this.gLDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string AuthTimekeeper {
        get {
            return this.authTimekeeperField;
        }
        set {
            this.authTimekeeperField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string SpvTimekeeper {
        get {
            return this.spvTimekeeperField;
        }
        set {
            this.spvTimekeeperField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ParCostIndex {
        get {
            return this.parCostIndexField;
        }
        set {
            this.parCostIndexField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string MatrixTaxCode {
        get {
            return this.matrixTaxCodeField;
        }
        set {
            this.matrixTaxCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Rpt1CurrRate {
        get {
            return this.rpt1CurrRateField;
        }
        set {
            this.rpt1CurrRateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Rpt2CurrRate {
        get {
            return this.rpt2CurrRateField;
        }
        set {
            this.rpt2CurrRateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Rpt3CurrRate {
        get {
            return this.rpt3CurrRateField;
        }
        set {
            this.rpt3CurrRateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Rpt1CurrRateStd {
        get {
            return this.rpt1CurrRateStdField;
        }
        set {
            this.rpt1CurrRateStdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Rpt2CurrRateStd {
        get {
            return this.rpt2CurrRateStdField;
        }
        set {
            this.rpt2CurrRateStdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Rpt3CurrRateStd {
        get {
            return this.rpt3CurrRateStdField;
        }
        set {
            this.rpt3CurrRateStdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string PrevProfMaster {
        get {
            return this.prevProfMasterField;
        }
        set {
            this.prevProfMasterField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ConversionRefNum {
        get {
            return this.conversionRefNumField;
        }
        set {
            this.conversionRefNumField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string WHTaxCode {
        get {
            return this.wHTaxCodeField;
        }
        set {
            this.wHTaxCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string WHTaxReason {
        get {
            return this.wHTaxReasonField;
        }
        set {
            this.wHTaxReasonField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string LastPurgeType {
        get {
            return this.lastPurgeTypeField;
        }
        set {
            this.lastPurgeTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Phase2 {
        get {
            return this.phase2Field;
        }
        set {
            this.phase2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Task2 {
        get {
            return this.task2Field;
        }
        set {
            this.task2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Activity2 {
        get {
            return this.activity2Field;
        }
        set {
            this.activity2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Description", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public CostCardDescription[] Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Number", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public CostCardNumber[] Number {
        get {
            return this.numberField;
        }
        set {
            this.numberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Code", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public CostCardCode[] Code {
        get {
            return this.codeField;
        }
        set {
            this.codeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class CostCardDescription {
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class CostCardNumber {
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class CostCardCode {
}

///// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
//[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
//public partial class NewDataSet {
    
//    private CostCard[] itemsField;
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute("CostCard")]
//    public CostCard[] Items {
//        get {
//            return this.itemsField;
//        }
//        set {
//            this.itemsField = value;
//        }
//    }
//}
