//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class MatterSrv {
    
    private string numberField;
    
    private string altNumberField;
    
    private string displayNameField;
    
    private string descriptionField;
    
    private string clientField;
    
    private string mattInfoField;
    
    private string relMattIndexField;
    
    private string mattStatusField;
    
    private string mattStatusDateField;
    
    private string mattTypeField;
    
    private string openDateField;
    
    private string conflictStatusField;
    
    private string narrativeField;
    
    private string billingInstrucField;
    
    private string languageField;
    
    private string contactInfoField;
    
    private string referralInfoField;
    
    private string mattCloseTypeField;
    
    private string closeDateField;
    
    private string isMasterField;
    
    private string nonBillTypeField;
    
    private string isProBonoField;
    
    private string proBonoEntityField;
    
    private string proBonoInfoField;
    
    private string isAdminField;
    
    private string adminAccountField;
    
    private string adminInfoField;
    
    private string elecBillingTypeField;
    
    private string elecNumberField;
    
    private string elecInfoField;
    
    private string isNonBillableField;
    
    private string billAsMatterField;
    
    private string billSiteField;
    
    private string statementSiteField;
    
    private string isValidateField;
    
    private string openTkprField;
    
    private string closeTkprField;
    
    private string commentsField;
    
    private string isDefaultField;
    
    private string billingFrequencyField;
    
    private string isNoProformaField;
    
    private string isNoBillField;
    
    private string markupField;
    
    private string withholdingTaxField;
    
    private string timeTaxCodeField;
    
    private string costTaxCodeField;
    
    private string chrgTaxCodeField;
    
    private string dueDaysField;
    
    private string currencyField;
    
    private string currencyDateListField;
    
    private string elecCostTypeMapField;
    
    private string timeIncrementField;
    
    private string isAutoNumberingField;
    
    private string isEngageLetterReqField;
    
    private string engageLetterSubDateField;
    
    private string engageLetterRecDateField;
    
    private string engageLetterCommentField;
    
    private string isWaiverLetterReqField;
    
    private string waiverLetterSubDateField;
    
    private string waiverLetterRecDateField;
    
    private string waiverLetterCommentField;
    
    private string isConflictsConfidentialField;
    
    private string billDCSTemplateField;
    
    private string profDCSTemplateField;
    
    private string stmtDCSTemplateField;
    
    private string isAutoNumAfterSaveField;
    
    private string approveTkprField;
    
    private string mattAttributeField;
    
    private string mattCategoryField;
    
    private string entryDateField;
    
    private string vATRegistrationField;
    
    private string mattMinTypeField;
    
    private string gLProjectField;
    
    private string isForeignField;
    
    private string volumeDiscountGroupField;
    
    private string mattInterestField;
    
    private string isEBillField;
    
    private string elecTitleMapField;
    
    private string elecDCSTemplateField;
    
    private string paymentTermsInfoField;
    
    private string isFeeEstimateField;
    
    private string feeEstimateAmountField;
    
    private string estimatedCompletionDateField;
    
    private string approveDateField;
    
    private string invoiceOverrideField;
    
    private string proformaEmailField;
    
    private string billEmailField;
    
    private string isNumberEnabledField;
    
    private string gLRespTkprField;
    
    private string isICBAcctRecField;
    
    private string isICBPayableField;
    
    private string iCBUnitDueToField;
    
    private string iCBUnitDueFromField;
    
    private string hasTimekeeperChangedField;
    
    private string isAllowTrustOverdrawField;
    
    private string billingOfficeField;
    
    private string bankAcctApField;
    
    private string taxReportID1Field;
    
    private string taxReportID2Field;
    
    private string toTaxAreaField;
    
    private string isLeadVolumeDiscountMatterField;
    
    private string isBillStatementIncludeDoubtfulField;
    
    private string loadGroupField;
    
    private string loadNumberField;
    
    private string loadSourceField;
    
    private string ebillValidationListField;
    
    private string wPTypeField;
    
    private string billTkprDispNameField;
    
    private string gLActivityField;
    
    private string creditNoteDCSTemplateField;
    
    private string elecTaxCodeMapField;
    
    private string billGroupDCSTemplateField;
    
    private string creditNoteGroupDCSTemplateField;
    
    private string day_CCCField;
    
    private string engSignedDate_CCCField;
    
    private string engStatus_CCCField;
    
    private string engType_CCCField;
    
    private string isEvergreen_CCCField;
    
    private string month_CCCField;
    
    private string opportunityID_CCCField;
    
    private string bD1Field;
    
    private string rTKField;

    private string mattIndex;

    public string MattIndex
    {
        get
        {
            return this.mattIndex;
        }
        set
        {
            this.mattIndex = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Number {
        get {
            return this.numberField;
        }
        set {
            this.numberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string AltNumber {
        get {
            return this.altNumberField;
        }
        set {
            this.altNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string DisplayName {
        get {
            return this.displayNameField;
        }
        set {
            this.displayNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Client {
        get {
            return this.clientField;
        }
        set {
            this.clientField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string MattInfo {
        get {
            return this.mattInfoField;
        }
        set {
            this.mattInfoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string RelMattIndex {
        get {
            return this.relMattIndexField;
        }
        set {
            this.relMattIndexField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string MattStatus {
        get {
            return this.mattStatusField;
        }
        set {
            this.mattStatusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string MattStatusDate {
        get {
            return this.mattStatusDateField;
        }
        set {
            this.mattStatusDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string MattType {
        get {
            return this.mattTypeField;
        }
        set {
            this.mattTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string OpenDate {
        get {
            return this.openDateField;
        }
        set {
            this.openDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ConflictStatus {
        get {
            return this.conflictStatusField;
        }
        set {
            this.conflictStatusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Narrative {
        get {
            return this.narrativeField;
        }
        set {
            this.narrativeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string BillingInstruc {
        get {
            return this.billingInstrucField;
        }
        set {
            this.billingInstrucField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Language {
        get {
            return this.languageField;
        }
        set {
            this.languageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ContactInfo {
        get {
            return this.contactInfoField;
        }
        set {
            this.contactInfoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ReferralInfo {
        get {
            return this.referralInfoField;
        }
        set {
            this.referralInfoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string MattCloseType {
        get {
            return this.mattCloseTypeField;
        }
        set {
            this.mattCloseTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CloseDate {
        get {
            return this.closeDateField;
        }
        set {
            this.closeDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string IsMaster {
        get {
            return this.isMasterField;
        }
        set {
            this.isMasterField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string NonBillType {
        get {
            return this.nonBillTypeField;
        }
        set {
            this.nonBillTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string IsProBono {
        get {
            return this.isProBonoField;
        }
        set {
            this.isProBonoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ProBonoEntity {
        get {
            return this.proBonoEntityField;
        }
        set {
            this.proBonoEntityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ProBonoInfo {
        get {
            return this.proBonoInfoField;
        }
        set {
            this.proBonoInfoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string IsAdmin {
        get {
            return this.isAdminField;
        }
        set {
            this.isAdminField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string AdminAccount {
        get {
            return this.adminAccountField;
        }
        set {
            this.adminAccountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string AdminInfo {
        get {
            return this.adminInfoField;
        }
        set {
            this.adminInfoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ElecBillingType {
        get {
            return this.elecBillingTypeField;
        }
        set {
            this.elecBillingTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ElecNumber {
        get {
            return this.elecNumberField;
        }
        set {
            this.elecNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ElecInfo {
        get {
            return this.elecInfoField;
        }
        set {
            this.elecInfoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string IsNonBillable {
        get {
            return this.isNonBillableField;
        }
        set {
            this.isNonBillableField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string BillAsMatter {
        get {
            return this.billAsMatterField;
        }
        set {
            this.billAsMatterField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string BillSite {
        get {
            return this.billSiteField;
        }
        set {
            this.billSiteField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string StatementSite {
        get {
            return this.statementSiteField;
        }
        set {
            this.statementSiteField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string IsValidate {
        get {
            return this.isValidateField;
        }
        set {
            this.isValidateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string OpenTkpr {
        get {
            return this.openTkprField;
        }
        set {
            this.openTkprField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CloseTkpr {
        get {
            return this.closeTkprField;
        }
        set {
            this.closeTkprField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Comments {
        get {
            return this.commentsField;
        }
        set {
            this.commentsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string IsDefault {
        get {
            return this.isDefaultField;
        }
        set {
            this.isDefaultField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string BillingFrequency {
        get {
            return this.billingFrequencyField;
        }
        set {
            this.billingFrequencyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string IsNoProforma {
        get {
            return this.isNoProformaField;
        }
        set {
            this.isNoProformaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string IsNoBill {
        get {
            return this.isNoBillField;
        }
        set {
            this.isNoBillField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Markup {
        get {
            return this.markupField;
        }
        set {
            this.markupField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string WithholdingTax {
        get {
            return this.withholdingTaxField;
        }
        set {
            this.withholdingTaxField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string TimeTaxCode {
        get {
            return this.timeTaxCodeField;
        }
        set {
            this.timeTaxCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CostTaxCode {
        get {
            return this.costTaxCodeField;
        }
        set {
            this.costTaxCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ChrgTaxCode {
        get {
            return this.chrgTaxCodeField;
        }
        set {
            this.chrgTaxCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string DueDays {
        get {
            return this.dueDaysField;
        }
        set {
            this.dueDaysField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Currency {
        get {
            return this.currencyField;
        }
        set {
            this.currencyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CurrencyDateList {
        get {
            return this.currencyDateListField;
        }
        set {
            this.currencyDateListField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ElecCostTypeMap {
        get {
            return this.elecCostTypeMapField;
        }
        set {
            this.elecCostTypeMapField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string TimeIncrement {
        get {
            return this.timeIncrementField;
        }
        set {
            this.timeIncrementField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string IsAutoNumbering {
        get {
            return this.isAutoNumberingField;
        }
        set {
            this.isAutoNumberingField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string IsEngageLetterReq {
        get {
            return this.isEngageLetterReqField;
        }
        set {
            this.isEngageLetterReqField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string EngageLetterSubDate {
        get {
            return this.engageLetterSubDateField;
        }
        set {
            this.engageLetterSubDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string EngageLetterRecDate {
        get {
            return this.engageLetterRecDateField;
        }
        set {
            this.engageLetterRecDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string EngageLetterComment {
        get {
            return this.engageLetterCommentField;
        }
        set {
            this.engageLetterCommentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string IsWaiverLetterReq {
        get {
            return this.isWaiverLetterReqField;
        }
        set {
            this.isWaiverLetterReqField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string WaiverLetterSubDate {
        get {
            return this.waiverLetterSubDateField;
        }
        set {
            this.waiverLetterSubDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string WaiverLetterRecDate {
        get {
            return this.waiverLetterRecDateField;
        }
        set {
            this.waiverLetterRecDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string WaiverLetterComment {
        get {
            return this.waiverLetterCommentField;
        }
        set {
            this.waiverLetterCommentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string IsConflictsConfidential {
        get {
            return this.isConflictsConfidentialField;
        }
        set {
            this.isConflictsConfidentialField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string BillDCSTemplate {
        get {
            return this.billDCSTemplateField;
        }
        set {
            this.billDCSTemplateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ProfDCSTemplate {
        get {
            return this.profDCSTemplateField;
        }
        set {
            this.profDCSTemplateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string StmtDCSTemplate {
        get {
            return this.stmtDCSTemplateField;
        }
        set {
            this.stmtDCSTemplateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string IsAutoNumAfterSave {
        get {
            return this.isAutoNumAfterSaveField;
        }
        set {
            this.isAutoNumAfterSaveField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ApproveTkpr {
        get {
            return this.approveTkprField;
        }
        set {
            this.approveTkprField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string MattAttribute {
        get {
            return this.mattAttributeField;
        }
        set {
            this.mattAttributeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string MattCategory {
        get {
            return this.mattCategoryField;
        }
        set {
            this.mattCategoryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string EntryDate {
        get {
            return this.entryDateField;
        }
        set {
            this.entryDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string VATRegistration {
        get {
            return this.vATRegistrationField;
        }
        set {
            this.vATRegistrationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string MattMinType {
        get {
            return this.mattMinTypeField;
        }
        set {
            this.mattMinTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string GLProject {
        get {
            return this.gLProjectField;
        }
        set {
            this.gLProjectField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string IsForeign {
        get {
            return this.isForeignField;
        }
        set {
            this.isForeignField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string VolumeDiscountGroup {
        get {
            return this.volumeDiscountGroupField;
        }
        set {
            this.volumeDiscountGroupField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string MattInterest {
        get {
            return this.mattInterestField;
        }
        set {
            this.mattInterestField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string IsEBill {
        get {
            return this.isEBillField;
        }
        set {
            this.isEBillField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ElecTitleMap {
        get {
            return this.elecTitleMapField;
        }
        set {
            this.elecTitleMapField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ElecDCSTemplate {
        get {
            return this.elecDCSTemplateField;
        }
        set {
            this.elecDCSTemplateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string PaymentTermsInfo {
        get {
            return this.paymentTermsInfoField;
        }
        set {
            this.paymentTermsInfoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string IsFeeEstimate {
        get {
            return this.isFeeEstimateField;
        }
        set {
            this.isFeeEstimateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string FeeEstimateAmount {
        get {
            return this.feeEstimateAmountField;
        }
        set {
            this.feeEstimateAmountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string EstimatedCompletionDate {
        get {
            return this.estimatedCompletionDateField;
        }
        set {
            this.estimatedCompletionDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ApproveDate {
        get {
            return this.approveDateField;
        }
        set {
            this.approveDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string InvoiceOverride {
        get {
            return this.invoiceOverrideField;
        }
        set {
            this.invoiceOverrideField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ProformaEmail {
        get {
            return this.proformaEmailField;
        }
        set {
            this.proformaEmailField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string BillEmail {
        get {
            return this.billEmailField;
        }
        set {
            this.billEmailField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string IsNumberEnabled {
        get {
            return this.isNumberEnabledField;
        }
        set {
            this.isNumberEnabledField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string GLRespTkpr {
        get {
            return this.gLRespTkprField;
        }
        set {
            this.gLRespTkprField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string IsICBAcctRec {
        get {
            return this.isICBAcctRecField;
        }
        set {
            this.isICBAcctRecField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string IsICBPayable {
        get {
            return this.isICBPayableField;
        }
        set {
            this.isICBPayableField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ICBUnitDueTo {
        get {
            return this.iCBUnitDueToField;
        }
        set {
            this.iCBUnitDueToField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ICBUnitDueFrom {
        get {
            return this.iCBUnitDueFromField;
        }
        set {
            this.iCBUnitDueFromField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string HasTimekeeperChanged {
        get {
            return this.hasTimekeeperChangedField;
        }
        set {
            this.hasTimekeeperChangedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string IsAllowTrustOverdraw {
        get {
            return this.isAllowTrustOverdrawField;
        }
        set {
            this.isAllowTrustOverdrawField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string BillingOffice {
        get {
            return this.billingOfficeField;
        }
        set {
            this.billingOfficeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string BankAcctAp {
        get {
            return this.bankAcctApField;
        }
        set {
            this.bankAcctApField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string TaxReportID1 {
        get {
            return this.taxReportID1Field;
        }
        set {
            this.taxReportID1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string TaxReportID2 {
        get {
            return this.taxReportID2Field;
        }
        set {
            this.taxReportID2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ToTaxArea {
        get {
            return this.toTaxAreaField;
        }
        set {
            this.toTaxAreaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string IsLeadVolumeDiscountMatter {
        get {
            return this.isLeadVolumeDiscountMatterField;
        }
        set {
            this.isLeadVolumeDiscountMatterField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string IsBillStatementIncludeDoubtful {
        get {
            return this.isBillStatementIncludeDoubtfulField;
        }
        set {
            this.isBillStatementIncludeDoubtfulField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string LoadGroup {
        get {
            return this.loadGroupField;
        }
        set {
            this.loadGroupField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string LoadNumber {
        get {
            return this.loadNumberField;
        }
        set {
            this.loadNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string LoadSource {
        get {
            return this.loadSourceField;
        }
        set {
            this.loadSourceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string EbillValidationList {
        get {
            return this.ebillValidationListField;
        }
        set {
            this.ebillValidationListField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string WPType {
        get {
            return this.wPTypeField;
        }
        set {
            this.wPTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string BillTkprDispName {
        get {
            return this.billTkprDispNameField;
        }
        set {
            this.billTkprDispNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string GLActivity {
        get {
            return this.gLActivityField;
        }
        set {
            this.gLActivityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CreditNoteDCSTemplate {
        get {
            return this.creditNoteDCSTemplateField;
        }
        set {
            this.creditNoteDCSTemplateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ElecTaxCodeMap {
        get {
            return this.elecTaxCodeMapField;
        }
        set {
            this.elecTaxCodeMapField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string BillGroupDCSTemplate {
        get {
            return this.billGroupDCSTemplateField;
        }
        set {
            this.billGroupDCSTemplateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CreditNoteGroupDCSTemplate {
        get {
            return this.creditNoteGroupDCSTemplateField;
        }
        set {
            this.creditNoteGroupDCSTemplateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Day_CCC {
        get {
            return this.day_CCCField;
        }
        set {
            this.day_CCCField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string EngSignedDate_CCC {
        get {
            return this.engSignedDate_CCCField;
        }
        set {
            this.engSignedDate_CCCField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string EngStatus_CCC {
        get {
            return this.engStatus_CCCField;
        }
        set {
            this.engStatus_CCCField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string EngType_CCC {
        get {
            return this.engType_CCCField;
        }
        set {
            this.engType_CCCField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string IsEvergreen_CCC {
        get {
            return this.isEvergreen_CCCField;
        }
        set {
            this.isEvergreen_CCCField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Month_CCC {
        get {
            return this.month_CCCField;
        }
        set {
            this.month_CCCField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string OpportunityID_CCC {
        get {
            return this.opportunityID_CCCField;
        }
        set {
            this.opportunityID_CCCField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string BD1 {
        get {
            return this.bD1Field;
        }
        set {
            this.bD1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string rTK {
        get {
            return this.rTKField;
        }
        set {
            this.rTKField = value;
        }
    }
}

///// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
//[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
//public partial class NewDataSet {
    
//    private MatterSrv[] itemsField;
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute("MatterSrv")]
//    public MatterSrv[] Items {
//        get {
//            return this.itemsField;
//        }
//        set {
//            this.itemsField = value;
//        }
//    }
//}
