//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class PGDetHdr_CCC {
    
    private string adjWIPField;
    
    private string blendedHourlyRateField;
    
    private string creditEstHighField;
    
    private string creditEstLowField;
    
    private string effStartField;
    
    private string feeCapPctField;
    
    private string isAuditDefenseIncludedField;
    
    private string nxEndDateField;
    
    private string origWIPField;
    
    private string remainingWIPField;
    
    private string totalField;
    
    private string feeCapFixedField;
    
    private string bA_Notes_CCCField;
    
    private string nxStartDateField;
    
    public string KeyValue { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string AdjWIP {
        get {
            return this.adjWIPField;
        }
        set {
            this.adjWIPField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string BlendedHourlyRate {
        get {
            return this.blendedHourlyRateField;
        }
        set {
            this.blendedHourlyRateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CreditEstHigh {
        get {
            return this.creditEstHighField;
        }
        set {
            this.creditEstHighField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CreditEstLow {
        get {
            return this.creditEstLowField;
        }
        set {
            this.creditEstLowField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string EffStart {
        get {
            return this.effStartField;
        }
        set {
            this.effStartField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string FeeCapPct {
        get {
            return this.feeCapPctField;
        }
        set {
            this.feeCapPctField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string IsAuditDefenseIncluded {
        get {
            return this.isAuditDefenseIncludedField;
        }
        set {
            this.isAuditDefenseIncludedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string NxEndDate {
        get {
            return this.nxEndDateField;
        }
        set {
            this.nxEndDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string OrigWIP {
        get {
            return this.origWIPField;
        }
        set {
            this.origWIPField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string RemainingWIP {
        get {
            return this.remainingWIPField;
        }
        set {
            this.remainingWIPField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Total {
        get {
            return this.totalField;
        }
        set {
            this.totalField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string FeeCapFixed {
        get {
            return this.feeCapFixedField;
        }
        set {
            this.feeCapFixedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string BA_Notes_CCC {
        get {
            return this.bA_Notes_CCCField;
        }
        set {
            this.bA_Notes_CCCField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string NxStartDate {
        get {
            return this.nxStartDateField;
        }
        set {
            this.nxStartDateField = value;
        }
    }
}

///// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
//[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
//public partial class NewDataSet {
    
//    private PGDetHdr_CCC[] itemsField;
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute("PGDetHdr_CCC")]
//    public PGDetHdr_CCC[] Items {
//        get {
//            return this.itemsField;
//        }
//        set {
//            this.itemsField = value;
//        }
//    }
//}
