//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class Timekeeper {
    
    private string timekeeperIDField;
    
    private string tkprIndexField;
    
    private string numberField;
    
    private string altNumberField;
    
    private string entityField;
    
    private string billNameField;
    
    private string billInitialField;
    
    private string tkprStatusField;
    
    private string sortNameField;
    
    private string gLTimekeeperField;
    
    private string gLValueField;
    
    private string languageField;
    
    private string narrativeField;
    
    private string narrative_FormattedTextField;
    
    private string payrollNumberField;
    
    private string physicalLocationField;
    
    private string hRTitleField;
    
    private string hRNumberField;
    
    private string jDDateField;
    
    private string compDateField;
    
    private string tkprTypeField;
    
    private string tkprAttributeField;
    
    private string tkprCategoryField;
    
    private string profDCSTemplateField;
    
    private string billDCSTemplateField;
    
    private string stmtDCSTemplateField;
    
    private string rateYearField;
    
    private string westLawUserIDNumField;
    
    private string westLawContactIDNumField;
    
    private string creditNoteDCSTemplateField;
    
    private string billGroupDCSTemplateField;
    
    private string creditNoteGroupDCSTemplateField;
    
    private string wF_UserField;
    
    private string baseUserNameField;
    
    private TimekeeperDisplayName[] displayNameField;
    
    private TimekeeperDescription[] descriptionField;
    
    private TimekeeperName[] nameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string TimekeeperID {
        get {
            return this.timekeeperIDField;
        }
        set {
            this.timekeeperIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string TkprIndex {
        get {
            return this.tkprIndexField;
        }
        set {
            this.tkprIndexField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Number {
        get {
            return this.numberField;
        }
        set {
            this.numberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string AltNumber {
        get {
            return this.altNumberField;
        }
        set {
            this.altNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Entity {
        get {
            return this.entityField;
        }
        set {
            this.entityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string BillName {
        get {
            return this.billNameField;
        }
        set {
            this.billNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string BillInitial {
        get {
            return this.billInitialField;
        }
        set {
            this.billInitialField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string TkprStatus {
        get {
            return this.tkprStatusField;
        }
        set {
            this.tkprStatusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string SortName {
        get {
            return this.sortNameField;
        }
        set {
            this.sortNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string GLTimekeeper {
        get {
            return this.gLTimekeeperField;
        }
        set {
            this.gLTimekeeperField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string GLValue {
        get {
            return this.gLValueField;
        }
        set {
            this.gLValueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Language {
        get {
            return this.languageField;
        }
        set {
            this.languageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Narrative {
        get {
            return this.narrativeField;
        }
        set {
            this.narrativeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Narrative_FormattedText {
        get {
            return this.narrative_FormattedTextField;
        }
        set {
            this.narrative_FormattedTextField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string PayrollNumber {
        get {
            return this.payrollNumberField;
        }
        set {
            this.payrollNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string PhysicalLocation {
        get {
            return this.physicalLocationField;
        }
        set {
            this.physicalLocationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string HRTitle {
        get {
            return this.hRTitleField;
        }
        set {
            this.hRTitleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string HRNumber {
        get {
            return this.hRNumberField;
        }
        set {
            this.hRNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string JDDate {
        get {
            return this.jDDateField;
        }
        set {
            this.jDDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CompDate {
        get {
            return this.compDateField;
        }
        set {
            this.compDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string TkprType {
        get {
            return this.tkprTypeField;
        }
        set {
            this.tkprTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string TkprAttribute {
        get {
            return this.tkprAttributeField;
        }
        set {
            this.tkprAttributeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string TkprCategory {
        get {
            return this.tkprCategoryField;
        }
        set {
            this.tkprCategoryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ProfDCSTemplate {
        get {
            return this.profDCSTemplateField;
        }
        set {
            this.profDCSTemplateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string BillDCSTemplate {
        get {
            return this.billDCSTemplateField;
        }
        set {
            this.billDCSTemplateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string StmtDCSTemplate {
        get {
            return this.stmtDCSTemplateField;
        }
        set {
            this.stmtDCSTemplateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string RateYear {
        get {
            return this.rateYearField;
        }
        set {
            this.rateYearField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string WestLawUserIDNum {
        get {
            return this.westLawUserIDNumField;
        }
        set {
            this.westLawUserIDNumField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string WestLawContactIDNum {
        get {
            return this.westLawContactIDNumField;
        }
        set {
            this.westLawContactIDNumField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CreditNoteDCSTemplate {
        get {
            return this.creditNoteDCSTemplateField;
        }
        set {
            this.creditNoteDCSTemplateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string BillGroupDCSTemplate {
        get {
            return this.billGroupDCSTemplateField;
        }
        set {
            this.billGroupDCSTemplateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CreditNoteGroupDCSTemplate {
        get {
            return this.creditNoteGroupDCSTemplateField;
        }
        set {
            this.creditNoteGroupDCSTemplateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string WF_User {
        get {
            return this.wF_UserField;
        }
        set {
            this.wF_UserField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string BaseUserName {
        get {
            return this.baseUserNameField;
        }
        set {
            this.baseUserNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("DisplayName", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public TimekeeperDisplayName[] DisplayName {
        get {
            return this.displayNameField;
        }
        set {
            this.displayNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Description", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public TimekeeperDescription[] Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Name", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public TimekeeperName[] Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class TimekeeperDisplayName {
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class TimekeeperDescription {
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class TimekeeperName {
}

/// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
//[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
//public partial class NewDataSet {
    
//    private Timekeeper[] itemsField;
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute("Timekeeper")]
//    public Timekeeper[] Items {
//        get {
//            return this.itemsField;
//        }
//        set {
//            this.itemsField = value;
//        }
//    }
//}
