//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class Voucher {
    
    private string voucherIDField;
    
    private string vchrIndexField;
    
    private string voucherNumField;
    
    private string tranDateField;
    
    private string invDateField;
    
    private string payeeField;
    
    private string currencyField;
    
    private string currDateField;
    
    private string amountField;
    
    private string aPTranTypeField;
    
    private string termsField;
    
    private string discountDateField;
    
    private string dueDateField;
    
    private string payDateField;
    
    private string openAmtField;
    
    private string poField;
    
    private string pOAmtField;
    
    private string officeField;
    
    private string payBankAcctField;
    
    private string aPGLAcctField;
    
    private string postDateField;
    
    private string isPrepaidField;
    
    private string commentsField;
    
    private string comments_FormattedTextField;
    
    private string ckSelField;
    
    private string isReversedField;
    
    private string reverseIndexField;
    
    private string reverseDateField;
    
    private string approvedAmtField;
    
    private string isDisplayReportsField;
    
    private string payeeSiteField;
    
    private string reverseReasonField;
    
    private string vchrStatusField;
    
    private string groupNumField;
    
    private string loadNumField;
    
    private string loadSourceField;
    
    private string isSeparateCheckField;
    
    private string unitCurrRateField;
    
    private string firmCurrRateField;
    
    private string taxDateField;
    
    private string vchrAutoNumberField;
    
    private string rpt1CurrRateField;
    
    private string rpt2CurrRateField;
    
    private string rpt3CurrRateField;
    
    private string fiscalInvNumField;
    
    private string vchrPayStatusListField;
    
    private string payeeAccountField;
    
    private string incurPayeeField;
    
    private string conversionRefNumField;
    
    private string withholdingTaxRefField;
    
    private string isZeroCkField;
    
    private string ckReqUserField;
    
    private string ckReqTimekeeperField;
    
    private string numberField;
    
    private string ckReqCommentsField;
    
    private string wF_VchrApproverField;
    
    private string wF_OfficePaymentField;
    
    private string wF_ReturnCheckToField;
    
    private string wF_ReturnToOfficeField;
    
    private string wF_DateNeededField;
    
    private VoucherInvNum[] invNumField;
    
    private VoucherName[] nameField;
    
    private VoucherDescription[] descriptionField;
    
    private VoucherPONum[] pONumField;
    
    private VoucherBaseUserName[] baseUserNameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string VoucherID {
        get {
            return this.voucherIDField;
        }
        set {
            this.voucherIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string VchrIndex {
        get {
            return this.vchrIndexField;
        }
        set {
            this.vchrIndexField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string VoucherNum {
        get {
            return this.voucherNumField;
        }
        set {
            this.voucherNumField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string TranDate {
        get {
            return this.tranDateField;
        }
        set {
            this.tranDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string InvDate {
        get {
            return this.invDateField;
        }
        set {
            this.invDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Payee {
        get {
            return this.payeeField;
        }
        set {
            this.payeeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Currency {
        get {
            return this.currencyField;
        }
        set {
            this.currencyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CurrDate {
        get {
            return this.currDateField;
        }
        set {
            this.currDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Amount {
        get {
            return this.amountField;
        }
        set {
            this.amountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string APTranType {
        get {
            return this.aPTranTypeField;
        }
        set {
            this.aPTranTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Terms {
        get {
            return this.termsField;
        }
        set {
            this.termsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string DiscountDate {
        get {
            return this.discountDateField;
        }
        set {
            this.discountDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string DueDate {
        get {
            return this.dueDateField;
        }
        set {
            this.dueDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string PayDate {
        get {
            return this.payDateField;
        }
        set {
            this.payDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string OpenAmt {
        get {
            return this.openAmtField;
        }
        set {
            this.openAmtField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string PO {
        get {
            return this.poField;
        }
        set {
            this.poField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string POAmt {
        get {
            return this.pOAmtField;
        }
        set {
            this.pOAmtField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Office {
        get {
            return this.officeField;
        }
        set {
            this.officeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string PayBankAcct {
        get {
            return this.payBankAcctField;
        }
        set {
            this.payBankAcctField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string APGLAcct {
        get {
            return this.aPGLAcctField;
        }
        set {
            this.aPGLAcctField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string PostDate {
        get {
            return this.postDateField;
        }
        set {
            this.postDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string IsPrepaid {
        get {
            return this.isPrepaidField;
        }
        set {
            this.isPrepaidField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Comments {
        get {
            return this.commentsField;
        }
        set {
            this.commentsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Comments_FormattedText {
        get {
            return this.comments_FormattedTextField;
        }
        set {
            this.comments_FormattedTextField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CkSel {
        get {
            return this.ckSelField;
        }
        set {
            this.ckSelField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string IsReversed {
        get {
            return this.isReversedField;
        }
        set {
            this.isReversedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ReverseIndex {
        get {
            return this.reverseIndexField;
        }
        set {
            this.reverseIndexField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ReverseDate {
        get {
            return this.reverseDateField;
        }
        set {
            this.reverseDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ApprovedAmt {
        get {
            return this.approvedAmtField;
        }
        set {
            this.approvedAmtField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string IsDisplayReports {
        get {
            return this.isDisplayReportsField;
        }
        set {
            this.isDisplayReportsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string PayeeSite {
        get {
            return this.payeeSiteField;
        }
        set {
            this.payeeSiteField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ReverseReason {
        get {
            return this.reverseReasonField;
        }
        set {
            this.reverseReasonField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string VchrStatus {
        get {
            return this.vchrStatusField;
        }
        set {
            this.vchrStatusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string GroupNum {
        get {
            return this.groupNumField;
        }
        set {
            this.groupNumField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string LoadNum {
        get {
            return this.loadNumField;
        }
        set {
            this.loadNumField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string LoadSource {
        get {
            return this.loadSourceField;
        }
        set {
            this.loadSourceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string IsSeparateCheck {
        get {
            return this.isSeparateCheckField;
        }
        set {
            this.isSeparateCheckField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string UnitCurrRate {
        get {
            return this.unitCurrRateField;
        }
        set {
            this.unitCurrRateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string FirmCurrRate {
        get {
            return this.firmCurrRateField;
        }
        set {
            this.firmCurrRateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string TaxDate {
        get {
            return this.taxDateField;
        }
        set {
            this.taxDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string VchrAutoNumber {
        get {
            return this.vchrAutoNumberField;
        }
        set {
            this.vchrAutoNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Rpt1CurrRate {
        get {
            return this.rpt1CurrRateField;
        }
        set {
            this.rpt1CurrRateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Rpt2CurrRate {
        get {
            return this.rpt2CurrRateField;
        }
        set {
            this.rpt2CurrRateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Rpt3CurrRate {
        get {
            return this.rpt3CurrRateField;
        }
        set {
            this.rpt3CurrRateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string FiscalInvNum {
        get {
            return this.fiscalInvNumField;
        }
        set {
            this.fiscalInvNumField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string VchrPayStatusList {
        get {
            return this.vchrPayStatusListField;
        }
        set {
            this.vchrPayStatusListField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string PayeeAccount {
        get {
            return this.payeeAccountField;
        }
        set {
            this.payeeAccountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string IncurPayee {
        get {
            return this.incurPayeeField;
        }
        set {
            this.incurPayeeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ConversionRefNum {
        get {
            return this.conversionRefNumField;
        }
        set {
            this.conversionRefNumField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string WithholdingTaxRef {
        get {
            return this.withholdingTaxRefField;
        }
        set {
            this.withholdingTaxRefField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string IsZeroCk {
        get {
            return this.isZeroCkField;
        }
        set {
            this.isZeroCkField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CkReqUser {
        get {
            return this.ckReqUserField;
        }
        set {
            this.ckReqUserField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CkReqTimekeeper {
        get {
            return this.ckReqTimekeeperField;
        }
        set {
            this.ckReqTimekeeperField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Number {
        get {
            return this.numberField;
        }
        set {
            this.numberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CkReqComments {
        get {
            return this.ckReqCommentsField;
        }
        set {
            this.ckReqCommentsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string WF_VchrApprover {
        get {
            return this.wF_VchrApproverField;
        }
        set {
            this.wF_VchrApproverField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string WF_OfficePayment {
        get {
            return this.wF_OfficePaymentField;
        }
        set {
            this.wF_OfficePaymentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string WF_ReturnCheckTo {
        get {
            return this.wF_ReturnCheckToField;
        }
        set {
            this.wF_ReturnCheckToField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string WF_ReturnToOffice {
        get {
            return this.wF_ReturnToOfficeField;
        }
        set {
            this.wF_ReturnToOfficeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string WF_DateNeeded {
        get {
            return this.wF_DateNeededField;
        }
        set {
            this.wF_DateNeededField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("InvNum", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public VoucherInvNum[] InvNum {
        get {
            return this.invNumField;
        }
        set {
            this.invNumField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Name", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public VoucherName[] Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Description", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public VoucherDescription[] Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("PONum", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public VoucherPONum[] PONum {
        get {
            return this.pONumField;
        }
        set {
            this.pONumField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("BaseUserName", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public VoucherBaseUserName[] BaseUserName {
        get {
            return this.baseUserNameField;
        }
        set {
            this.baseUserNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class VoucherInvNum {
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class VoucherName {
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class VoucherDescription {
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class VoucherPONum {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class VoucherBaseUserName {
}

///// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
//[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
//public partial class NewDataSet {
    
//    private Voucher[] itemsField;
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute("Voucher")]
//    public Voucher[] Items {
//        get {
//            return this.itemsField;
//        }
//        set {
//            this.itemsField = value;
//        }
//    }
//}
