//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 

namespace TE3EConnect.te3eOjects.ClientSE
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class Client
    {

        private string entityField;

        private string numberField;

        private string altNumberField;

        private string displayNameField;

        private string sortStringField;

        private string relatedClientField;

        private string cliTypeField;

        private string cliStatusTypeField;

        private string cliStatusDateField;

        private string creditLimitField;

        private string currencyField;

        private string currencyDateField;

        private string openDateField;

        private string invoiceSiteField;

        private string statementSiteField;

        private string contactInfoField;

        private string industryField;

        private string narrativeField;

        private string languageField;

        private string isPayorField;

        private string payorIndexField;

        private string billingInstrucField;

        private string descriptionField;

        private string openTkprField;

        private string closeTkprField;

        private string closeDateField;

        private string isAutoNumberingField;

        private string billDCSTemplateField;

        private string stmtDCSTemplateField;

        private string countryField;

        private string cliAttributeField;

        private string cliCategoryField;

        private string entryDateField;

        private string vATRegistrationField;

        private string isEngageLetterReqField;

        private string engageLetterSubDateField;

        private string engageLetterRecDateField;

        private string engageLetterCommentField;

        private string isWaiverLetterReqField;

        private string waiverLetterSubDateField;

        private string waiverLetterRecDateField;

        private string waiverLetterCommentField;

        private string isConflictsConfidentialField;

        private string approveTkprField;

        private string conflictStatusField;

        private string profDCSTemplateField;

        private string isIdentifiedField;

        private string identificationDateField;

        private string volumeDiscountGroupField;

        private string isEBillField;

        private string dueDaysField;

        private string approveDateField;

        private string isOrigClosedStatusField;

        private string isNumberEnabledField;

        private string isCreateTaxInvOnRcptField;

        private string isICBField;

        private string iCBUnitField;

        private string stmtSitePrimPhoneField;

        private string invSitePrimPhoneField;

        private string payorTaxAreaField;

        private string payorTaxNumField;

        private string isNewEntityField;

        private string newEntityIndexField;

        private string loadGroupField;

        private string loadNumberField;

        private string loadSourceField;

        private string rSSFeedField;

        private string tickerSymbolField;

        private string uRLField;

        private string creditNoteDCSTemplateField;

        private string billGroupDCSTemplateField;

        private string creditNoteGroupDCSTemplateField;

        private string isNoTC_CCCField;

        public string ClientIndex { get; set; }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Entity
        {
            get
            {
                return this.entityField;
            }
            set
            {
                this.entityField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Number
        {
            get
            {
                return this.numberField;
            }
            set
            {
                this.numberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AltNumber
        {
            get
            {
                return this.altNumberField;
            }
            set
            {
                this.altNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DisplayName
        {
            get
            {
                return this.displayNameField;
            }
            set
            {
                this.displayNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SortString
        {
            get
            {
                return this.sortStringField;
            }
            set
            {
                this.sortStringField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RelatedClient
        {
            get
            {
                return this.relatedClientField;
            }
            set
            {
                this.relatedClientField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CliType
        {
            get
            {
                return this.cliTypeField;
            }
            set
            {
                this.cliTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CliStatusType
        {
            get
            {
                return this.cliStatusTypeField;
            }
            set
            {
                this.cliStatusTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CliStatusDate
        {
            get
            {
                return this.cliStatusDateField;
            }
            set
            {
                this.cliStatusDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CreditLimit
        {
            get
            {
                return this.creditLimitField;
            }
            set
            {
                this.creditLimitField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Currency
        {
            get
            {
                return this.currencyField;
            }
            set
            {
                this.currencyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CurrencyDate
        {
            get
            {
                return this.currencyDateField;
            }
            set
            {
                this.currencyDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OpenDate
        {
            get
            {
                return this.openDateField;
            }
            set
            {
                this.openDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string InvoiceSite
        {
            get
            {
                return this.invoiceSiteField;
            }
            set
            {
                this.invoiceSiteField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string StatementSite
        {
            get
            {
                return this.statementSiteField;
            }
            set
            {
                this.statementSiteField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ContactInfo
        {
            get
            {
                return this.contactInfoField;
            }
            set
            {
                this.contactInfoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Industry
        {
            get
            {
                return this.industryField;
            }
            set
            {
                this.industryField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Narrative
        {
            get
            {
                return this.narrativeField;
            }
            set
            {
                this.narrativeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Language
        {
            get
            {
                return this.languageField;
            }
            set
            {
                this.languageField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IsPayor
        {
            get
            {
                return this.isPayorField;
            }
            set
            {
                this.isPayorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PayorIndex
        {
            get
            {
                return this.payorIndexField;
            }
            set
            {
                this.payorIndexField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BillingInstruc
        {
            get
            {
                return this.billingInstrucField;
            }
            set
            {
                this.billingInstrucField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OpenTkpr
        {
            get
            {
                return this.openTkprField;
            }
            set
            {
                this.openTkprField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CloseTkpr
        {
            get
            {
                return this.closeTkprField;
            }
            set
            {
                this.closeTkprField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CloseDate
        {
            get
            {
                return this.closeDateField;
            }
            set
            {
                this.closeDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IsAutoNumbering
        {
            get
            {
                return this.isAutoNumberingField;
            }
            set
            {
                this.isAutoNumberingField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BillDCSTemplate
        {
            get
            {
                return this.billDCSTemplateField;
            }
            set
            {
                this.billDCSTemplateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string StmtDCSTemplate
        {
            get
            {
                return this.stmtDCSTemplateField;
            }
            set
            {
                this.stmtDCSTemplateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Country
        {
            get
            {
                return this.countryField;
            }
            set
            {
                this.countryField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CliAttribute
        {
            get
            {
                return this.cliAttributeField;
            }
            set
            {
                this.cliAttributeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CliCategory
        {
            get
            {
                return this.cliCategoryField;
            }
            set
            {
                this.cliCategoryField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EntryDate
        {
            get
            {
                return this.entryDateField;
            }
            set
            {
                this.entryDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string VATRegistration
        {
            get
            {
                return this.vATRegistrationField;
            }
            set
            {
                this.vATRegistrationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IsEngageLetterReq
        {
            get
            {
                return this.isEngageLetterReqField;
            }
            set
            {
                this.isEngageLetterReqField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EngageLetterSubDate
        {
            get
            {
                return this.engageLetterSubDateField;
            }
            set
            {
                this.engageLetterSubDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EngageLetterRecDate
        {
            get
            {
                return this.engageLetterRecDateField;
            }
            set
            {
                this.engageLetterRecDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EngageLetterComment
        {
            get
            {
                return this.engageLetterCommentField;
            }
            set
            {
                this.engageLetterCommentField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IsWaiverLetterReq
        {
            get
            {
                return this.isWaiverLetterReqField;
            }
            set
            {
                this.isWaiverLetterReqField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string WaiverLetterSubDate
        {
            get
            {
                return this.waiverLetterSubDateField;
            }
            set
            {
                this.waiverLetterSubDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string WaiverLetterRecDate
        {
            get
            {
                return this.waiverLetterRecDateField;
            }
            set
            {
                this.waiverLetterRecDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string WaiverLetterComment
        {
            get
            {
                return this.waiverLetterCommentField;
            }
            set
            {
                this.waiverLetterCommentField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IsConflictsConfidential
        {
            get
            {
                return this.isConflictsConfidentialField;
            }
            set
            {
                this.isConflictsConfidentialField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ApproveTkpr
        {
            get
            {
                return this.approveTkprField;
            }
            set
            {
                this.approveTkprField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ConflictStatus
        {
            get
            {
                return this.conflictStatusField;
            }
            set
            {
                this.conflictStatusField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ProfDCSTemplate
        {
            get
            {
                return this.profDCSTemplateField;
            }
            set
            {
                this.profDCSTemplateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IsIdentified
        {
            get
            {
                return this.isIdentifiedField;
            }
            set
            {
                this.isIdentifiedField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IdentificationDate
        {
            get
            {
                return this.identificationDateField;
            }
            set
            {
                this.identificationDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string VolumeDiscountGroup
        {
            get
            {
                return this.volumeDiscountGroupField;
            }
            set
            {
                this.volumeDiscountGroupField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IsEBill
        {
            get
            {
                return this.isEBillField;
            }
            set
            {
                this.isEBillField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DueDays
        {
            get
            {
                return this.dueDaysField;
            }
            set
            {
                this.dueDaysField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ApproveDate
        {
            get
            {
                return this.approveDateField;
            }
            set
            {
                this.approveDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IsOrigClosedStatus
        {
            get
            {
                return this.isOrigClosedStatusField;
            }
            set
            {
                this.isOrigClosedStatusField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IsNumberEnabled
        {
            get
            {
                return this.isNumberEnabledField;
            }
            set
            {
                this.isNumberEnabledField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IsCreateTaxInvOnRcpt
        {
            get
            {
                return this.isCreateTaxInvOnRcptField;
            }
            set
            {
                this.isCreateTaxInvOnRcptField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IsICB
        {
            get
            {
                return this.isICBField;
            }
            set
            {
                this.isICBField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ICBUnit
        {
            get
            {
                return this.iCBUnitField;
            }
            set
            {
                this.iCBUnitField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string StmtSitePrimPhone
        {
            get
            {
                return this.stmtSitePrimPhoneField;
            }
            set
            {
                this.stmtSitePrimPhoneField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string InvSitePrimPhone
        {
            get
            {
                return this.invSitePrimPhoneField;
            }
            set
            {
                this.invSitePrimPhoneField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PayorTaxArea
        {
            get
            {
                return this.payorTaxAreaField;
            }
            set
            {
                this.payorTaxAreaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PayorTaxNum
        {
            get
            {
                return this.payorTaxNumField;
            }
            set
            {
                this.payorTaxNumField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IsNewEntity
        {
            get
            {
                return this.isNewEntityField;
            }
            set
            {
                this.isNewEntityField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NewEntityIndex
        {
            get
            {
                return this.newEntityIndexField;
            }
            set
            {
                this.newEntityIndexField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LoadGroup
        {
            get
            {
                return this.loadGroupField;
            }
            set
            {
                this.loadGroupField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LoadNumber
        {
            get
            {
                return this.loadNumberField;
            }
            set
            {
                this.loadNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LoadSource
        {
            get
            {
                return this.loadSourceField;
            }
            set
            {
                this.loadSourceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RSSFeed
        {
            get
            {
                return this.rSSFeedField;
            }
            set
            {
                this.rSSFeedField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TickerSymbol
        {
            get
            {
                return this.tickerSymbolField;
            }
            set
            {
                this.tickerSymbolField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string URL
        {
            get
            {
                return this.uRLField;
            }
            set
            {
                this.uRLField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CreditNoteDCSTemplate
        {
            get
            {
                return this.creditNoteDCSTemplateField;
            }
            set
            {
                this.creditNoteDCSTemplateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BillGroupDCSTemplate
        {
            get
            {
                return this.billGroupDCSTemplateField;
            }
            set
            {
                this.billGroupDCSTemplateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CreditNoteGroupDCSTemplate
        {
            get
            {
                return this.creditNoteGroupDCSTemplateField;
            }
            set
            {
                this.creditNoteGroupDCSTemplateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IsNoTC_CCC
        {
            get
            {
                return this.isNoTC_CCCField;
            }
            set
            {
                this.isNoTC_CCCField = value;
            }
        }
    }

    ///// <remarks/>
    //[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    //[System.SerializableAttribute()]
    //[System.Diagnostics.DebuggerStepThroughAttribute()]
    //[System.ComponentModel.DesignerCategoryAttribute("code")]
    //[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    //[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    //public partial class NewDataSet
    //{

    //    private Client[] itemsField;

    //    /// <remarks/>
    //    [System.Xml.Serialization.XmlElementAttribute("Client")]
    //    public Client[] Items
    //    {
    //        get
    //        {
    //            return this.itemsField;
    //        }
    //        set
    //        {
    //            this.itemsField = value;
    //        }
    //    }
    //}
}