//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TE3EEntityFramework.Datasource.RCGKENTCMS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMSAssignment
    {
        public int Id { get; set; }
        public Nullable<int> E3EID { get; set; }
        public string KenticoID { get; set; }
        public Nullable<int> MatterIndex { get; set; }
        public string MatterNumber { get; set; }
        public string MatterName { get; set; }
        public Nullable<int> ClientIndex { get; set; }
        public string ClientNumber { get; set; }
        public string ClientName { get; set; }
        public Nullable<int> RelatedMatter { get; set; }
        public string MattStatus { get; set; }
        public string MattStatusDesc { get; set; }
        public Nullable<System.DateTime> MattStatusDate { get; set; }
        public Nullable<System.DateTime> OpenDate { get; set; }
        public string Narrative { get; set; }
        public string Narrative_UnformattedText { get; set; }
        public Nullable<System.DateTime> CloseDate { get; set; }
        public string ElecBillingType { get; set; }
        public string ElecBillingTypeDesc { get; set; }
        public string ElectronicNumber { get; set; }
        public Nullable<int> OpenTimekeeper { get; set; }
        public string OpenTimekeeperName { get; set; }
        public Nullable<int> CloseTimekeeper { get; set; }
        public string CloseTimekeeperName { get; set; }
        public string FeesTaxCode { get; set; }
        public string FeeTaxCodeDesc { get; set; }
        public string Currency { get; set; }
        public string CurrencyDesc { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<byte> EBilling { get; set; }
        public Nullable<System.DateTime> DateOccurence { get; set; }
        public string DateOfOccurenceTxt { get; set; }
        public Nullable<byte> IsProspective_CCC { get; set; }
        public Nullable<byte> IsCheckWritingAuthority { get; set; }
        public Nullable<byte> WebOriginated { get; set; }
        public Nullable<decimal> RetainerAmount { get; set; }
        public string ScopeOfWork { get; set; }
        public Nullable<byte> FixedPrice { get; set; }
        public string DNENotes { get; set; }
        public Nullable<byte> IsConfLetterStd { get; set; }
        public Nullable<byte> IsConfLetterLegal { get; set; }
        public Nullable<byte> IsConfLetterNatAgmt { get; set; }
        public Nullable<byte> IsConfLetterEngSvcs { get; set; }
        public Nullable<byte> IsConfLetterCAT { get; set; }
        public Nullable<byte> IsConfLetterRtnr { get; set; }
        public Nullable<byte> IsConfLetterSign { get; set; }
        public string ROFTemplate { get; set; }
        public string ROFTemplateDesc { get; set; }
        public Nullable<System.DateTime> StartDate1 { get; set; }
        public Nullable<int> BillingTimekeeper { get; set; }
        public string BillingTimekeeperName { get; set; }
        public Nullable<int> ResponsibleTimekeeper { get; set; }
        public string ResponsibleTimekeeperName { get; set; }
        public Nullable<int> SupervisingTimekeeper { get; set; }
        public string SupervisingTimekeeperName { get; set; }
        public string Office { get; set; }
        public string OfficeName { get; set; }
        public string Arrangement { get; set; }
        public string ArrangementDesc { get; set; }
        public string Section { get; set; }
        public string SectionDesc { get; set; }
        public string Department { get; set; }
        public string DepartmentDesc { get; set; }
        public string PracticeGroup { get; set; }
        public string PracticeGroupDesc { get; set; }
        public string PTAGroup { get; set; }
        public string PTAGroupDesc { get; set; }
        public string IndustryGroup { get; set; }
        public string IndustryGroupDesc { get; set; }
        public Nullable<int> TechnicalReviewerNumber { get; set; }
        public string TechincalReviewerName { get; set; }
        public Nullable<int> EngineerOfRecordNo { get; set; }
        public string EngineerOfRecordName { get; set; }
        public Nullable<int> BDManagerNo { get; set; }
        public string BDManagerName { get; set; }
        public Nullable<System.DateTime> StartDate2 { get; set; }
        public string SpecialClientInstruction { get; set; }
        public string SpecialClientInstructionDesc { get; set; }
        public string SpecialInstructions { get; set; }
        public string InvoiceTo { get; set; }
        public string Rate { get; set; }
        public string RateDesc { get; set; }
        public string RateExceptGroup { get; set; }
        public string RateExceptGroupDesc { get; set; }
        public string TimeType { get; set; }
        public string TimeTypeDesc { get; set; }
        public Nullable<decimal> FlatFeeAmount { get; set; }
        public Nullable<decimal> Budget { get; set; }
        public string InsuranceType { get; set; }
        public string InsuranceTypeDesc { get; set; }
        public string ClaimType { get; set; }
        public string ClaimTypeDesc { get; set; }
        public string ReportTo { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
        public string QueueType { get; set; }
        public Nullable<bool> IsProcessed { get; set; }
        public string ErrorMsg { get; set; }
        public Nullable<System.DateTime> ProcessedDate { get; set; }
        public Nullable<int> NumOfAttempts { get; set; }
        public string SubmissionID { get; set; }
    }
}
