//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TE3EEntityFramework.Datasource.RCGKENTCMS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMSCustomerProfileAudit
    {
        public int Id { get; set; }
        public string KenticoID { get; set; }
        public string ClientNumber { get; set; }
        public Nullable<int> ContactID { get; set; }
        public string Email { get; set; }
        public string Salutation { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Phone { get; set; }
        public string CompanyName { get; set; }
        public string CompanyType { get; set; }
        public string CompanyAddress1 { get; set; }
        public string CompanyAddress2 { get; set; }
        public string CompanyAddressCity { get; set; }
        public string CompanyAddressState { get; set; }
        public string CompanyAddressZip { get; set; }
        public string CompanyAddressCountry { get; set; }
        public Nullable<decimal> CompanyAddressLon { get; set; }
        public Nullable<decimal> CompanyAddressLat { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
        public string QueueType { get; set; }
        public Nullable<bool> IsProcessed { get; set; }
        public string ErrorMsg { get; set; }
        public Nullable<System.DateTime> ProcessedDate { get; set; }
        public Nullable<int> NumOfAttempts { get; set; }
        public System.DateTime UpdatedAt { get; set; }
        public string Operation { get; set; }
    }
}
