//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TE3EEntityFramework.Datasource.RCGKENTCMS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMSKenticoCustomerRelAudit
    {
        public int Id { get; set; }
        public string KenticoID { get; set; }
        public string ClientNumber { get; set; }
        public string ClientName { get; set; }
        public string ClientType { get; set; }
        public Nullable<int> ContactID { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public string Operation { get; set; }
    }
}
