//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TE3EEntityFramework.Datasource.RCGKENTCMS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMSOfficeEmailLookup
    {
        public int Id { get; set; }
        public string Office { get; set; }
        public string Code { get; set; }
        public string County { get; set; }
        public string OfficeEmail { get; set; }
        public string State { get; set; }
        public string StateAbbreviation { get; set; }
    }
}
